services:
  browser-test:
    build:
      context: ../../..
      dockerfile: kuml-web/.delivery/Dockerfile
      target: browser-test
      provenance: false
    volumes:
      - ../../tests/.output:/output
    environment:
      KUML_WEB_URL: http://127.0.0.1:8080
